# Generated by Django 4.1 on 2022-08-06 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2048)),
                ('init_amount', models.IntegerField()),
                ('final_amount', models.IntegerField()),
                ('start_age', models.IntegerField()),
                ('end_age', models.IntegerField()),
            ],
        ),
    ]
